# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/chandra/computational/maxwellDist

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/chandra/computational/maxwellDist

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/chandra/computational/maxwellDist/CMakeFiles /home/chandra/computational/maxwellDist/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/chandra/computational/maxwellDist/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named MaxwellDist

# Build rule for target.
MaxwellDist: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 MaxwellDist
.PHONY : MaxwellDist

# fast build rule for target.
MaxwellDist/fast:
	$(MAKE) -f CMakeFiles/MaxwellDist.dir/build.make CMakeFiles/MaxwellDist.dir/build
.PHONY : MaxwellDist/fast

#=============================================================================
# Target rules for targets named Particle

# Build rule for target.
Particle: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Particle
.PHONY : Particle

# fast build rule for target.
Particle/fast:
	$(MAKE) -f CMakeFiles/Particle.dir/build.make CMakeFiles/Particle.dir/build
.PHONY : Particle/fast

#=============================================================================
# Target rules for targets named Vector

# Build rule for target.
Vector: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Vector
.PHONY : Vector

# fast build rule for target.
Vector/fast:
	$(MAKE) -f CMakeFiles/Vector.dir/build.make CMakeFiles/Vector.dir/build
.PHONY : Vector/fast

#=============================================================================
# Target rules for targets named main.exe

# Build rule for target.
main.exe: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 main.exe
.PHONY : main.exe

# fast build rule for target.
main.exe/fast:
	$(MAKE) -f CMakeFiles/main.exe.dir/build.make CMakeFiles/main.exe.dir/build
.PHONY : main.exe/fast

Particle.o: Particle.cxx.o
.PHONY : Particle.o

# target to build an object file
Particle.cxx.o:
	$(MAKE) -f CMakeFiles/Particle.dir/build.make CMakeFiles/Particle.dir/Particle.cxx.o
.PHONY : Particle.cxx.o

Particle.i: Particle.cxx.i
.PHONY : Particle.i

# target to preprocess a source file
Particle.cxx.i:
	$(MAKE) -f CMakeFiles/Particle.dir/build.make CMakeFiles/Particle.dir/Particle.cxx.i
.PHONY : Particle.cxx.i

Particle.s: Particle.cxx.s
.PHONY : Particle.s

# target to generate assembly for a file
Particle.cxx.s:
	$(MAKE) -f CMakeFiles/Particle.dir/build.make CMakeFiles/Particle.dir/Particle.cxx.s
.PHONY : Particle.cxx.s

Vector2d.o: Vector2d.cxx.o
.PHONY : Vector2d.o

# target to build an object file
Vector2d.cxx.o:
	$(MAKE) -f CMakeFiles/Vector.dir/build.make CMakeFiles/Vector.dir/Vector2d.cxx.o
.PHONY : Vector2d.cxx.o

Vector2d.i: Vector2d.cxx.i
.PHONY : Vector2d.i

# target to preprocess a source file
Vector2d.cxx.i:
	$(MAKE) -f CMakeFiles/Vector.dir/build.make CMakeFiles/Vector.dir/Vector2d.cxx.i
.PHONY : Vector2d.cxx.i

Vector2d.s: Vector2d.cxx.s
.PHONY : Vector2d.s

# target to generate assembly for a file
Vector2d.cxx.s:
	$(MAKE) -f CMakeFiles/Vector.dir/build.make CMakeFiles/Vector.dir/Vector2d.cxx.s
.PHONY : Vector2d.cxx.s

main.o: main.cxx.o
.PHONY : main.o

# target to build an object file
main.cxx.o:
	$(MAKE) -f CMakeFiles/main.exe.dir/build.make CMakeFiles/main.exe.dir/main.cxx.o
.PHONY : main.cxx.o

main.i: main.cxx.i
.PHONY : main.i

# target to preprocess a source file
main.cxx.i:
	$(MAKE) -f CMakeFiles/main.exe.dir/build.make CMakeFiles/main.exe.dir/main.cxx.i
.PHONY : main.cxx.i

main.s: main.cxx.s
.PHONY : main.s

# target to generate assembly for a file
main.cxx.s:
	$(MAKE) -f CMakeFiles/main.exe.dir/build.make CMakeFiles/main.exe.dir/main.cxx.s
.PHONY : main.cxx.s

maxwellDist.o: maxwellDist.cxx.o
.PHONY : maxwellDist.o

# target to build an object file
maxwellDist.cxx.o:
	$(MAKE) -f CMakeFiles/MaxwellDist.dir/build.make CMakeFiles/MaxwellDist.dir/maxwellDist.cxx.o
.PHONY : maxwellDist.cxx.o

maxwellDist.i: maxwellDist.cxx.i
.PHONY : maxwellDist.i

# target to preprocess a source file
maxwellDist.cxx.i:
	$(MAKE) -f CMakeFiles/MaxwellDist.dir/build.make CMakeFiles/MaxwellDist.dir/maxwellDist.cxx.i
.PHONY : maxwellDist.cxx.i

maxwellDist.s: maxwellDist.cxx.s
.PHONY : maxwellDist.s

# target to generate assembly for a file
maxwellDist.cxx.s:
	$(MAKE) -f CMakeFiles/MaxwellDist.dir/build.make CMakeFiles/MaxwellDist.dir/maxwellDist.cxx.s
.PHONY : maxwellDist.cxx.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... MaxwellDist"
	@echo "... Particle"
	@echo "... Vector"
	@echo "... edit_cache"
	@echo "... main.exe"
	@echo "... rebuild_cache"
	@echo "... Particle.o"
	@echo "... Particle.i"
	@echo "... Particle.s"
	@echo "... Vector2d.o"
	@echo "... Vector2d.i"
	@echo "... Vector2d.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... maxwellDist.o"
	@echo "... maxwellDist.i"
	@echo "... maxwellDist.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

